# Generated by Django 3.0.2 on 2020-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='comments_per_day',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='last_comment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
