# Generated by Django 3.0.2 on 2020-08-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='preferences',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
