# Generated by Django 3.0.2 on 2020-08-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileinfo_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='preferences',
        ),
    ]
