# Generated by Django 3.0.2 on 2020-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200723_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
