# Generated by Django 3.0.2 on 2020-08-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileinfo_preferences'),
        ('blog', '0016_auto_20200803_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_list', to='accounts.ProfileInfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('post', 'author'), name='unique_pref'),
        ),
    ]
