# Generated by Django 3.0.2 on 2020-08-03 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20200803_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preference',
            name='post',
            field=models.ForeignKey(limit_choices_to=models.Q(published_date__isnull=False), on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
