# Generated by Django 3.0.2 on 2020-08-07 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200804_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 7)),
        ),
        migrations.CreateModel(
            name='Additionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='post_images/%Y/%m.%d/')),
                ('additional_img1', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m.%d/')),
                ('additional_img2', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m.%d/')),
                ('additional_link1', models.URLField(blank=True, null=True)),
                ('additional_link2', models.URLField(blank=True, null=True)),
                ('additional_link3', models.URLField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
