# Generated by Django 3.0.2 on 2020-08-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200807_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionals',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m.%d/'),
        ),
        migrations.AlterField(
            model_name='additionals',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='blog.Post'),
        ),
    ]
