# Generated by Django 3.0.2 on 2020-08-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200809_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_image',
            name='image',
            field=models.ImageField(upload_to='post_images/%Y.%m'),
        ),
    ]
