# Generated by Django 3.0.2 on 2020-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200812_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
