# Generated by Django 3.0.2 on 2020-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_additional_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_image',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
