# Generated by Django 3.0.2 on 2020-08-22 20:09

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200822_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
