# Generated by Django 3.0.2 on 2020-08-27 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200827_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 27, 16, 43, 33, 764815, tzinfo=utc)),
        ),
    ]
